export interface Product {
  id: number;
  name: string;
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  description: string;
  images: string[];
  category: string;
  brand: string;
  ageCategories: string[];
  quantities: string[];
  // Enhanced fields for search and filtering
  searchIndex: string; // Combined searchable text
  tags: string[]; // Tags for filtering and search
  petType: string; // Dog, Cat, Fish, Small Pet, Bird, etc.
  nutritionalInfo?: {
    protein?: string;
    fat?: string;
    fiber?: string;
    moisture?: string;
  };
  specialFeatures: string[]; // Grain-free, Organic, High-protein, etc.
  targetLife: string[]; // Puppy, Adult, Senior, All Life Stages
  flavor?: string; // Chicken, Beef, Fish, etc.
  weight: string; // Primary weight/size
  inStock: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Royal Canin Maxi Adult Dry Dog Food - 15kg",
    price: 4500,
    originalPrice: 5200,
    discount: 13,
    rating: 4.7,
    description:
      "Royal Canin Maxi Adult is specifically designed for large breed dogs (26-44kg) aged 15 months to 5 years. This formula supports healthy digestion, joint health, and maintains ideal weight with precise nutrition tailored for large breeds.",
    images: [
      "https://m.media-amazon.com/images/I/71nFVE2t0HL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/81p3cZoK2qL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71xTccspTGL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71JleyYLj6L._SX466_.jpg",
    ],
    category: "Dog Food",
    brand: "Royal Canin",
    ageCategories: ["Adult"],
    quantities: ["4kg", "10kg", "15kg"],
    searchIndex:
      "royal canin maxi adult large breed dog food joint health digestion nutrition",
    tags: [
      "dog",
      "adult",
      "large breed",
      "joint health",
      "digestion",
      "premium",
    ],
    petType: "Dog",
    specialFeatures: [
      "Large Breed Formula",
      "Joint Support",
      "Digestive Health",
      "Weight Management",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken",
    weight: "15kg",
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 2,
    name: "Whiskas Ocean Fish Adult Cat Food - 3kg",
    price: 850,
    originalPrice: 950,
    discount: 11,
    rating: 4.4,
    description:
      "Whiskas Ocean Fish provides complete and balanced nutrition for adult cats with real ocean fish. Enriched with Vitamin A for good vision, Vitamin E for healthy skin, and antioxidants for immune support.",
    images: [
      "https://m.media-amazon.com/images/I/71kQ6sr+bNL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71NoSSYytvL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/81bxjwsyPGL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/61EhoHv7Q9L._SX466_.jpg",
    ],
    category: "Cat Food",
    brand: "Whiskas",
    ageCategories: ["Adult"],
    quantities: ["1.2kg", "3kg", "7kg"],
    searchIndex:
      "whiskas ocean fish cat food vitamin antioxidants immune support vision",
    tags: [
      "cat",
      "adult",
      "ocean fish",
      "vitamins",
      "immune support",
      "balanced nutrition",
    ],
    petType: "Cat",
    specialFeatures: [
      "Real Ocean Fish",
      "Vitamin A",
      "Vitamin E", 
      "Antioxidants",
      "Complete Nutrition",
    ],
    targetLife: ["Adult"],
    flavor: "Ocean Fish",
    weight: "3kg",
    inStock: true,
  },
  {
    id: 3,
    name: "Pedigree Puppy Chicken & Milk - 1.2kg",
    price: 320,
    originalPrice: 380,
    discount: 16,
    rating: 4.5,
    description:
      "Pedigree Puppy food with Chicken & Milk provides essential nutrients for growing puppies. DHA for brain development, calcium for strong bones, and high-quality protein for healthy growth.",
    images: [
      "https://m.media-amazon.com/images/I/61sbRrU9PBL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71xTccspTGL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/81sbNHGclRL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71l17zmvVzL._SX466_.jpg",
    ],
    category: "Dog Food",
    brand: "Pedigree",
    ageCategories: ["Puppy"],
    quantities: ["480g", "1.2kg", "3kg"],
    searchIndex:
      "pedigree puppy chicken milk dha brain development calcium bones protein growth",
    tags: [
      "dog",
      "puppy",
      "chicken",
      "milk",
      "brain development",
      "bone health",
      "growth",
    ],
    petType: "Dog",
    specialFeatures: [
      "DHA for Brain Development",
      "Calcium Rich",
      "High-Quality Protein",
      "Essential Nutrients",
    ],
    targetLife: ["Puppy"],
    flavor: "Chicken & Milk",
    weight: "1.2kg",
    inStock: true,
    isNew: true,
  },
  {
    id: 4,
    name: "Hill's Science Diet Kitten Chicken Recipe - 2kg",
    price: 1200,
    originalPrice: 1350,
    discount: 11,
    rating: 4.8,
    description:
      "Hill's Science Diet Kitten provides precise nutrition for kittens up to 1 year. Made with high-quality chicken and enriched with DHA from fish oil for healthy brain and eye development.",
    images: [
      "https://m.media-amazon.com/images/I/81WVzsIOzpL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71SsCKRiv9L._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71pDqgsjF+L._SX466_.jpg",
      "https://m.media-amazon.com/images/I/81TLcYNUNgL._SX466_.jpg",
    ],
    category: "Cat Food",
    brand: "Hill's Science Diet",
    ageCategories: ["Kitten"],
    quantities: ["400g", "2kg", "4kg"],
    searchIndex:
      "hills science diet kitten chicken recipe dha fish oil brain eye development",
    tags: [
      "cat",
      "kitten",
      "chicken",
      "dha",
      "brain development",
      "eye development",
      "premium",
    ],
    petType: "Cat",
    specialFeatures: [
      "DHA from Fish Oil",
      "Brain Development",
      "Eye Development",
      "High-Quality Chicken",
      "Precise Nutrition",
    ],
    targetLife: ["Kitten"],
    flavor: "Chicken",
    weight: "2kg",
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 5,
    name: "Purina Pro Plan Adult Small Breed Dog Food - 2.5kg",
    price: 1100,
    originalPrice: 1250,
    discount: 12,
    rating: 4.6,
    description:
      "Purina Pro Plan for small breed dogs with real chicken as the first ingredient. Smaller kibble size perfect for small mouths, with high protein to support an ideal body condition.",
    images: [
      "https://m.media-amazon.com/images/I/71BdAbA9D7L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81Odu0ucTgS._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71yRZLDkl4L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71-Ga3gClqL._SX522_.jpg",
    ],
    category: "Dog Food",
    brand: "Purina Pro Plan",
    ageCategories: ["Adult"],
    quantities: ["800g", "2.5kg", "7kg"],
    searchIndex:
      "purina pro plan small breed dog food chicken kibble high protein ideal body condition",
    tags: [
      "dog",
      "adult",
      "small breed",
      "chicken",
      "high protein",
      "small kibble",
      "body condition",
    ],
    petType: "Dog",
    specialFeatures: [
      "Real Chicken First",
      "Small Kibble Size",
      "High Protein",
      "Small Breed Formula",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken",
    weight: "2.5kg",
    inStock: true,
  },
  {
    id: 6,
    name: "Farmina N&D Grain Free Chicken & Pomegranate Dog Food - 2.5kg",
    price: 1800,
    originalPrice: 2000,
    discount: 10,
    rating: 4.9,
    description:
      "Farmina N&D Grain Free formula with 70% animal ingredients, 30% vegetables & fruits. Made with fresh chicken, pomegranate, and blueberries. No grains, artificial preservatives, or GMO ingredients.",
    images: [
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSuB09Z2-Z7v0iBugs1J3FecqiSFmQ-ZllugtRAuolZLgVt_dN3ad4-Mi-GiAb4juKaTrHg64bsAxZix_pDMliUYCp30ziuWR9c1NwEb0UeapsieoRRylZk&usqp=CAE",
      "https://m.media-amazon.com/images/I/71Skptfd6KL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/71u0NWk2PDL._SY879_.jpg",
      "https://m.media-amazon.com/images/I/51ClQt+vynL.jpg",
    ],
    category: "Dog Food",
    brand: "Farmina",
    ageCategories: ["Adult"],
    quantities: ["800g", "2.5kg", "12kg"],
    searchIndex:
      "farmina nd grain free chicken pomegranate animal ingredients vegetables fruits artificial preservatives gmo",
    tags: [
      "dog",
      "adult",
      "grain free",
      "chicken",
      "pomegranate",
      "natural",
      "premium",
      "no gmo",
    ],
    petType: "Dog",
    specialFeatures: [
      "Grain Free",
      "70% Animal Ingredients",
      "No Artificial Preservatives",
      "No GMO",
      "Fresh Chicken",
      "Antioxidant Rich",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken & Pomegranate",
    weight: "2.5kg",
    inStock: true,
    isNew: true,
  },
  {
    id: 7,
    name: "Royal Canin Persian Adult Cat Food - 2kg",
    price: 1450,
    originalPrice: 1600,
    discount: 9,
    rating: 4.8,
    description:
      "Royal Canin Persian Adult is specially designed for Persian cats over 12 months. The unique kidney-shaped kibble is easy to grasp and chew. Supports skin and coat health with omega-3 and omega-6 fatty acids.",
    images: [
      "https://m.media-amazon.com/images/I/71krmfpgpjl._SX679_.jpg",
      "https://m.media-amazon.com/images/I/81p3cZoK2qL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71NoSSYytvL._SX466_.jpg",
      "https://5.imimg.com/data5/ECOM/Default/2024/1/378810208/RF/HJ/GK/12142841/71krmfpgpjl-sx679.jpg",
    ],
    category: "Cat Food",
    brand: "Royal Canin",
    ageCategories: ["Adult"],
    quantities: ["400g", "2kg", "4kg"],
    searchIndex:
      "royal canin persian cat food kidney shaped kibble omega fatty acids skin coat health",
    tags: [
      "cat",
      "adult",
      "persian",
      "breed specific",
      "kidney kibble",
      "omega fatty acids",
      "coat health",
    ],
    petType: "Cat",
    specialFeatures: [
      "Breed Specific",
      "Kidney-Shaped Kibble",
      "Omega-3 & Omega-6",
      "Skin & Coat Health",
      "Easy to Grasp",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken",
    weight: "2kg",
    inStock: true,
  },
  {
    id: 8,
    name: "Drools Focus Super Premium Adult Dog Food - 3kg",
    price: 680,
    originalPrice: 750,
    discount: 9,
    rating: 4.3,
    description:
      "Drools Focus Super Premium with real chicken as the first ingredient. Enriched with prebiotics for digestive health, omega fatty acids for skin & coat, and antioxidants for immune support.",
    images: [
      "https://m.media-amazon.com/images/I/71BdAbA9D7L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61sbRrU9PBL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71xTccspTGL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/81sbNHGclRL._SX466_.jpg",
    ],
    category: "Dog Food",
    brand: "Drools",
    ageCategories: ["Adult"],
    quantities: ["1.2kg", "3kg", "10kg"],
    searchIndex:
      "drools focus super premium dog food chicken prebiotics digestive health omega antioxidants immune support",
    tags: [
      "dog",
      "adult",
      "super premium",
      "chicken",
      "prebiotics",
      "digestive health",
      "immune support",
    ],
    petType: "Dog",
    specialFeatures: [
      "Real Chicken First",
      "Prebiotics",
      "Digestive Health",
      "Omega Fatty Acids",
      "Antioxidants",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken",
    weight: "3kg",
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 9,
    name: "Me-O Gold Persian Adult Cat Food - 1.3kg",
    price: 580,
    originalPrice: 650,
    discount: 11,
    rating: 4.4,
    description:
      "Me-O Gold Persian Adult Cat Food is specially formulated for Persian cats with long, thick coats. Contains taurine for heart health, vitamin E for skin, and reduces hairball formation.",
    images: [
      "https://petsnpets.com/cdn/shop/files/MiowMiowAdultTunaFishCatFood1.2kg.png?v=1716185686&width=1000",
      "https://m.media-amazon.com/images/I/71kQ6sr+bNL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71NoSSYytvL._SX466_.jpg",
      "https://5.imimg.com/data5/ECOM/Default/2024/1/378810208/RF/HJ/GK/12142841/71krmfpgpjl-sx679.jpg",
    ],
    category: "Cat Food",
    brand: "Me-O",
    ageCategories: ["Adult"],
    quantities: ["400g", "1.3kg", "3kg"],
    searchIndex:
      "meo gold persian cat food taurine heart health vitamin e skin hairball formation",
    tags: [
      "cat",
      "adult",
      "persian",
      "taurine",
      "heart health",
      "vitamin e",
      "hairball control",
    ],
    petType: "Cat",
    specialFeatures: [
      "Persian Breed Formula",
      "Taurine for Heart",
      "Vitamin E",
      "Hairball Control",
      "Long Coat Support",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken & Fish",
    weight: "1.3kg",
    inStock: true,
  },
  {
    id: 10,
    name: "Orijen Original Grain-Free Dog Food - 2kg",
    price: 3200,
    originalPrice: 3500,
    discount: 9,
    rating: 4.9,
    description:
      "Orijen Original features 85% quality animal ingredients including free-run chicken and turkey, wild-caught fish, and cage-free eggs. Grain-free with fresh regional ingredients, freeze-dried for peak nutrition.",
    images: [
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSuB09Z2-Z7v0iBugs1J3FecqiSFmQ-ZllugtRAuolZLgVt_dN3ad4-Mi-GiAb4juKaTrHg64bsAxZix_pDMliUYCp30ziuWR9c1NwEb0UeapsieoRRylZk&usqp=CAE",
      "https://m.media-amazon.com/images/I/71Skptfd6KL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/71u0NWk2PDL._SY879_.jpg",
      "https://m.media-amazon.com/images/I/71BdAbA9D7L._SX522_.jpg",
    ],
    category: "Dog Food",
    brand: "Orijen",
    ageCategories: ["Adult"],
    quantities: ["340g", "2kg", "6kg", "11.4kg"],
    searchIndex:
      "orijen original grain free dog food animal ingredients chicken turkey fish eggs freeze dried nutrition",
    tags: [
      "dog",
      "adult",
      "grain free",
      "premium",
      "chicken",
      "turkey",
      "fish",
      "freeze dried",
      "regional ingredients",
    ],
    petType: "Dog",
    specialFeatures: [
      "85% Animal Ingredients",
      "Grain-Free",
      "Free-Run Poultry",
      "Wild-Caught Fish",
      "Freeze-Dried",
      "Regional Ingredients",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken & Turkey",
    weight: "2kg",
    inStock: true,
    isNew: true,
  },
  {
    id: 11,
    name: "IAMS Proactive Health Healthy Digestion Dog Food - 3kg",
    price: 1150,
    originalPrice: 1300,
    discount: 12,
    rating: 4.5,
    description:
      "IAMS Proactive Health Healthy Digestion with prebiotics and beet pulp to support digestive health. Real chicken is the first ingredient, tailored nutrition for optimal digestion and nutrient absorption.",
    images: [
      "https://m.media-amazon.com/images/I/81Odu0ucTgS._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71yRZLDkl4L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61sbRrU9PBL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71xTccspTGL._SX466_.jpg",
    ],
    category: "Dog Food",
    brand: "IAMS",
    ageCategories: ["Adult"],
    quantities: ["1.5kg", "3kg", "12kg"],
    searchIndex:
      "iams proactive health healthy digestion prebiotics beet pulp chicken digestive health nutrient absorption",
    tags: [
      "dog",
      "adult",
      "digestive health",
      "prebiotics",
      "chicken",
      "beet pulp",
      "nutrient absorption",
    ],
    petType: "Dog",
    specialFeatures: [
      "Digestive Health",
      "Prebiotics",
      "Beet Pulp",
      "Real Chicken First",
      "Nutrient Absorption",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken",
    weight: "3kg",
    inStock: true,
  },
  {
    id: 12,
    name: "Purina Felix As Good As It Looks Adult Cat Food - Mixed Pack 12x85g",
    price: 420,
    originalPrice: 480,
    discount: 13,
    rating: 4.3,
    description:
      "Purina Felix wet cat food variety pack with delicious chunks in jelly. Contains essential vitamins and minerals for complete nutrition. Four delicious flavors: chicken, beef, salmon, and duck.",
    images: [
      "https://petsnpets.com/cdn/shop/files/MiowMiowAdultTunaFishCatFood1.2kg.png?v=1716185686&width=1000",
      "https://m.media-amazon.com/images/I/71kQ6sr+bNL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81WVzsIOzpL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71SsCKRiv9L._SX466_.jpg",
    ],
    category: "Cat Food",
    brand: "Purina Felix",
    ageCategories: ["Adult"],
    quantities: ["12x85g", "24x85g", "40x85g"],
    searchIndex:
      "purina felix wet cat food chunks jelly vitamins minerals chicken beef salmon duck",
    tags: [
      "cat",
      "adult",
      "wet food",
      "chunks in jelly",
      "variety pack",
      "vitamins",
      "minerals",
      "complete nutrition",
    ],
    petType: "Cat",
    specialFeatures: [
      "Wet Food",
      "Chunks in Jelly",
      "4 Flavors",
      "Complete Nutrition",
      "Essential Vitamins",
    ],
    targetLife: ["Adult"],
    flavor: "Mixed (Chicken, Beef, Salmon, Duck)",
    weight: "12x85g",
    inStock: true,
  },
  {
    id: 13,
    name: "Taste of the Wild High Prairie Puppy Food - 2kg",
    price: 1800,
    originalPrice: 2000,
    discount: 10,
    rating: 4.7,
    description:
      "Taste of the Wild High Prairie Puppy Formula with roasted bison and roasted venison. Grain-free with sweet potatoes and peas for highly digestible energy. DHA for brain development.",
    images: [
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSuB09Z2-Z7v0iBugs1J3FecqiSFmQ-ZllugtRAuolZLgVt_dN3ad4-Mi-GiAb4juKaTrHg64bsAxZix_pDMliUYCp30ziuWR9c1NwEb0UeapsieoRRylZk&usqp=CAE",
      "https://m.media-amazon.com/images/I/71Skptfd6KL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/61sbRrU9PBL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71xTccspTGL._SX466_.jpg",
    ],
    category: "Dog Food",
    brand: "Taste of the Wild",
    ageCategories: ["Puppy"],
    quantities: ["2kg", "5.6kg", "12.7kg"],
    searchIndex:
      "taste wild high prairie puppy bison venison grain free sweet potatoes peas dha brain development",
    tags: [
      "dog",
      "puppy",
      "grain free",
      "bison",
      "venison",
      "sweet potatoes",
      "dha",
      "brain development",
      "premium",
    ],
    petType: "Dog",
    specialFeatures: [
      "Grain-Free",
      "Roasted Bison",
      "Roasted Venison",
      "DHA for Brain Development",
      "Sweet Potatoes",
      "Highly Digestible",
    ],
    targetLife: ["Puppy"],
    flavor: "Bison & Venison",
    weight: "2kg",
    inStock: true,
    isNew: true,
  },
  {
    id: 14,
    name: "Acana Wild Prairie Regional Dog Food - 2kg",
    price: 2400,
    originalPrice: 2700,
    discount: 11,
    rating: 4.8,
    description:
      "Acana Wild Prairie features free-run chicken, turkey, cage-free eggs, and wild-caught fish. 60% meat, 40% vegetables and fruits. No grain, potato, or tapioca - just fresh regional ingredients.",
    images: [
      "https://m.media-amazon.com/images/I/71BdAbA9D7L._SX522_.jpg",
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSuB09Z2-Z7v0iBugs1J3FecqiSFmQ-ZllugtRAuolZLgVt_dN3ad4-Mi-GiAb4juKaTrHg64bsAxZix_pDMliUYCp30ziuWR9c1NwEb0UeapsieoRRylZk&usqp=CAE",
      "https://m.media-amazon.com/images/I/71Skptfd6KL._SY679_.jpg",
      "https://m.media-amazon.com/images/I/71u0NWk2PDL._SY879_.jpg",
    ],
    category: "Dog Food",
    brand: "Acana",
    ageCategories: ["Adult"],
    quantities: ["340g", "2kg", "6kg", "11.4kg"],
    searchIndex:
      "acana wild prairie chicken turkey eggs fish meat vegetables fruits grain free potato tapioca regional ingredients",
    tags: [
      "dog",
      "adult",
      "free-run chicken",
      "turkey",
      "wild-caught fish",
      "60% meat",
      "no grain",
      "regional ingredients",
      "premium",
    ],
    petType: "Dog",
    specialFeatures: [
      "60% Meat",
      "Free-Run Poultry",
      "Wild-Caught Fish",
      "No Grain/Potato/Tapioca",
      "Regional Ingredients",
      "40% Vegetables & Fruits",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken & Turkey",
    weight: "2kg",
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 15,
    name: "Blue Buffalo Life Protection Formula Adult Dog Food - 2.7kg",
    price: 1600,
    originalPrice: 1800,
    discount: 11,
    rating: 4.6,
    description:
      "Blue Buffalo Life Protection Formula with real chicken, whole grains, and antioxidant-rich LifeSource Bits. No chicken by-product meals, corn, wheat, soy, or artificial preservatives.",
    images: [
      "https://m.media-amazon.com/images/I/81Odu0ucTgS._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71yRZLDkl4L._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61sbRrU9PBL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71-Ga3gClqL._SX522_.jpg",
    ],
    category: "Dog Food",
    brand: "Blue Buffalo",
    ageCategories: ["Adult"],
    quantities: ["680g", "2.7kg", "6.8kg", "13.6kg"],
    searchIndex:
      "blue buffalo life protection formula chicken whole grains antioxidant lifesource bits by-product meals corn wheat soy artificial preservatives",
    tags: [
      "dog",
      "adult",
      "real chicken",
      "whole grains",
      "antioxidants",
      "lifesource bits",
      "no by-products",
      "natural",
    ],
    petType: "Dog",
    specialFeatures: [
      "Real Chicken First",
      "LifeSource Bits",
      "Antioxidant-Rich",
      "No By-Product Meals",
      "No Artificial Preservatives",
      "Whole Grains",
    ],
    targetLife: ["Adult"],
    flavor: "Chicken",
    weight: "2.7kg",
    inStock: true,
  },
  {
    id: 16,
    name: "Sheba Perfect Portions Wet Cat Food Trays - 12x37.5g",
    price: 390,
    originalPrice: 450,
    discount: 13,
    rating: 4.5,
    description:
      "Sheba Perfect Portions wet cat food in convenient twin-pack trays. Made with real meat and fish, no artificial flavors or preservatives. Perfect portion control for cats.",
    images: [
      "https://petsnpets.com/cdn/shop/files/MiowMiowAdultTunaFishCatFood1.2kg.png?v=1716185686&width=1000",
      "https://m.media-amazon.com/images/I/71kQ6sr+bNL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81WVzsIOzpL._SX466_.jpg",
      "https://m.media-amazon.com/images/I/71SsCKRiv9L._SX466_.jpg",
    ],
    category: "Cat Food",
    brand: "Sheba",
    ageCategories: ["Adult"],
    quantities: ["12x37.5g", "24x37.5g", "48x37.5g"],
    searchIndex:
      "sheba perfect portions wet cat food twin pack trays real meat fish artificial flavors preservatives portion control",
    tags: [
      "cat",
      "adult",
      "wet food",
      "perfect portions",
      "twin pack",
      "real meat",
      "no artificial",
      "portion control",
    ],
    petType: "Cat",
    specialFeatures: [
      "Perfect Portions",
      "Twin-Pack Trays",
      "Real Meat & Fish",
      "No Artificial Flavors",
      "No Preservatives",
      "Portion Control",
    ],
    targetLife: ["Adult"],
    flavor: "Mixed Varieties",
    weight: "12x37.5g",
    inStock: true,
  },
  
];
